### PR TITLE
Operational again

### PR DESCRIPTION
**Pull request by mrquincle**
Hi Matthias,

Just made this thing operational for the rocket launcher I got for christmas. This one has an LED and the command structure was slightly different.

This version works on the following more recent OS version:

```
Linux 3.16.0-29-generic #39-Ubuntu SMP Mon Dec 15 22:27:29 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Cheers,

Anne

### CODE REVIEW

**Comment by mavam** [comment]
Thanks for taking the time to make this toy fly again!

The changes look fine overall, I'll just add a few comments inline before merging.

**Comment by mrquincle** [comment]
#ifdefs are fine with me

**Comment by mavam** [comment]
I'll reopen the PR, you can simply push to your master branch to add new commits (and optionally squash 'em).

**Comment by mrquincle** [comment]
Done.

**Comment by mavam** [comment]
Cool, thanks for your efforts!

**Comment by mrquincle** [comment]
You're welcome! Back to hacking the memoto. :-)

**Pull request merged**
